### ISSUE TITLE
Fix styles on main program. 

### ISSUE THREAD

**Issue by smunoz1988** [Mukaba/cinema_showcase#2]
Great job, Jean Luis, on the progress you have made so far in your GitHub repository. We believe that you have the potential to produce an excellent product. To improve further, we recommend the following changes: 🤪🤪

-check on the main program. the cards padding is a little smaller than the original design. 

Your code is awesome! Pretty nice way to do it, keep it that way!

**Comment by Mukaba** [comment]
Thanks for your suggestions, I fixed them
